const colors = require("tailwindcss/colors");

module.exports = {
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {
      backgroundImage: (theme) => ({
        "bg-home": "url('/background/bg-home.png')",
        internal: "url('/background/bg-internal.png')",
      }),
      colors: {
        teal: {
          900: "#1d3941",
          800: "#29a3a3",
          700: "#2fbcbc",
          600: "#39e4c5",
          DEFAULT: "#35F0D0",
          500: "#35F0D0",
          400: "#64f2d9",
          300: "#8bf6e3",
          200: "#b0f8ec",
          100: "#8bf6e3",
        },
        black: {
          60: "rgba(17, 17, 17, 0.6)",
          ...colors.black,
        },
        purple: {
          400: "rgba(165, 151, 250, 1)",
        },
        white: colors.white,
        gray: colors.gray,
        indigo: colors.indigo,
        red: colors.red,
        yellow: colors.yellow,
      },
      height: {
        "42rem": "42rem",
        "50rem": "50rem",
        "62rem": "62rem",
      },
      fontSize: (fontSizes) => ({
        // sm: ['14px', '20px'],
        // base: ['16px', '24px'],
        // lg: ['20px', '28px'], // line height!
        // xl: ['24px', '32px'],
        xxxxxs: "0.5rem",
        xxxxs: "0.625rem",
        xxxs: "0.685rem",
        xxs: "0.735rem",
        xs: "0.8rem",
        // sm: "1.125rem",
        // base: "1.25rem",
        // lg: "1.25rem",
        // xl: "1.5rem",
        // "2xl": "1.875rem",
        // "3xl": "2.25rem",
        // "4xl": "2.5rem",
        // "5xl": "3rem",
        // "6xl": "4rem",
        // "7xl": "5rem",
        // "8xl": "6rem",
        // "9xl": "7rem",
        // "10xl": "8rem",
        ...fontSizes,
      }),
      fontFamily: {
        sans: [
          "Titillium Web",
          "Roboto",
          "Helvetica Neue",
          "Arial",
          "Noto Sans",
          "sans-serif",
          "Apple Color Emoji",
          "Segoe UI Emoji",
          "Segoe UI Symbol",
          "Noto Color Emoji",
        ],
        serif: [
          "Titillium Web",
          "Roboto",
          "Helvetica Neue",
          "Arial",
          "Noto Sans",
          "sans-serif",
          "Apple Color Emoji",
          "Segoe UI Emoji",
          "Segoe UI Symbol",
          "Noto Color Emoji",
        ],
        mono: [
          "DM Mono",
          "Courier",
          "Roboto",
          "Helvetica Neue",
          "Arial",
          "Noto Sans",
          "sans-serif",
          "Apple Color Emoji",
          "Segoe UI Emoji",
          "Segoe UI Symbol",
          "Noto Color Emoji",
        ],
      },
    },
  },
  variants: {
    // extend: {},
  },
  // plugins: [],
};
